# Game Settings
MAP_WIDTH = 2000
MAP_HEIGHT = 2000

PLAYER_START_MASS = 10
PLAYER_DEFAULT_NAME_PREFIX = "Player"
PLAYER_EAT_MASS_FACTOR = 1.10
PLAYER_MIN_MASS_TO_SPLIT = 35
PLAYER_MAX_CELLS = 16
CELL_SPLIT_PROPULSION = 75
CELL_MERGE_TIME = 15

# Mass Ejection
MASS_EJECT_AMOUNT = 10
MASS_EJECT_COST = 12
MASS_EJECT_SPEED = 400
MASS_EJECT_MIN_MASS = 25
EJECTED_MASS_RADIUS = 4
EJECTED_MASS_LIFESPAN = 30
EJECTED_MASS_FRICTION = 0.98

# Viruses
VIRUS_MASS = 100                     # Default mass of a virus
VIRUS_RADIUS_BASE_FACTOR = 10        # Used in: sqrt(mass / PI) * factor to get radius
MAX_VIRUSES = 15
VIRUS_SPLIT_PLAYER_MASS_FACTOR = 1.1
VIRUS_MAX_MASS_BEFORE_SPLIT = 150
VIRUS_FEED_MASS_GAIN = MASS_EJECT_AMOUNT
VIRUS_CELL_SPLIT_COUNT_MIN = 7
VIRUS_CELL_SPLIT_COUNT_MAX = 10
VIRUS_SPLIT_PROPULSION_FACTOR = 1.2

PELLET_MASS = 1
PELLET_RADIUS = 3
MAX_PELLETS = 150
PELLET_SPAWN_ATTEMPTS = 10

# Server and Game Loop
SERVER_TICK_RATE = 1/30
GAME_LOOP_DELAY = 1/60
PLAYER_AREA_OF_INTEREST_RADIUS = 2000 # Max distance to send entity updates to a player

# Leaderboard
LEADERBOARD_SIZE = 10
LEADERBOARD_UPDATE_INTERVAL = 2 # seconds

PLAYER_BASE_SPEED = 220

WEBSOCKET_MAX_SIZE = None
WEBSOCKET_MAX_QUEUE = None
ID_LENGTH = 6

# Logging
LOG_LEVEL = "INFO"
DEBUG_GAME_LOGIC = False # Set to True for detailed game logic print statements in server/game.py
